if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "INPUT, OUTPUT and SYMBOL are required")
endif()

string(REPLACE "\"" "" INPUT "${INPUT}")
string(REPLACE "\"" "" OUTPUT "${OUTPUT}")
file(TO_CMAKE_PATH "${INPUT}" INPUT_INCBIN)
string(REPLACE "\"" "\\\"" INPUT_INCBIN "${INPUT_INCBIN}")

string(LENGTH "${SYMBOL}" SYMBOL_LENGTH)
set(END_SYMBOL "${SYMBOL}End")
string(LENGTH "${END_SYMBOL}" END_SYMBOL_LENGTH)
set(MANGLED_SYMBOL "_ZN8neopanel6assets${SYMBOL_LENGTH}${SYMBOL}E")
set(MANGLED_END_SYMBOL "_ZN8neopanel6assets${END_SYMBOL_LENGTH}${END_SYMBOL}E")

file(WRITE "${OUTPUT}" "#include <cstddef>\n#include <cstdint>\n\n")
file(APPEND "${OUTPUT}" "namespace neopanel::assets {\n")
file(APPEND "${OUTPUT}" "extern const std::uint8_t ${SYMBOL}[];\n")
file(APPEND "${OUTPUT}" "extern const std::uint8_t ${END_SYMBOL}[];\n")
file(APPEND "${OUTPUT}" "extern const std::size_t ${SYMBOL}Size = reinterpret_cast<std::uintptr_t>(${END_SYMBOL}) - reinterpret_cast<std::uintptr_t>(${SYMBOL});\n")
file(APPEND "${OUTPUT}" "} // namespace neopanel::assets\n")
file(APPEND "${OUTPUT}" "\n")
file(APPEND "${OUTPUT}" "asm(\n")
file(APPEND "${OUTPUT}" "\".section .rodata\\n\"\n")
file(APPEND "${OUTPUT}" "\".balign 16\\n\"\n")
file(APPEND "${OUTPUT}" "\".global ${MANGLED_SYMBOL}\\n\"\n")
file(APPEND "${OUTPUT}" "\".global ${MANGLED_END_SYMBOL}\\n\"\n")
file(APPEND "${OUTPUT}" "\"${MANGLED_SYMBOL}:\\n\"\n")
file(APPEND "${OUTPUT}" "\".incbin \\\"${INPUT_INCBIN}\\\"\\n\"\n")
file(APPEND "${OUTPUT}" "\"${MANGLED_END_SYMBOL}:\\n\"\n")
file(APPEND "${OUTPUT}" "\".balign 16\\n\"\n")
file(APPEND "${OUTPUT}" ");\n")
